tokenizer_name: "bert-base-uncased"

training:
    max_step: 10000
    val_freq: 1000
    test_freq: 2000

hydra:
    run:
        dir: ./

defaults:
    - dataset: spider
    - dataloader: base
    - parser: ratsqlExtended
    - model: ratsql
    - optimizer: adam
    - loss: crossEntropy
