tokenizer_name: "bert-base-uncased"

training:
    max_step: 10000
    val_freq: 1000
    test_freq: 2000
optim_args:
    lr: 1e-3

defaults:
    - dataset: spider
    - dataloader: base
    - parser: ratsqlExtended
    - model: ratsql
    - optimizer: adam
    - loss: crossEntropy
